version: "3"

services:
  mongo_db:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  node_app:
    container_name: nodejs_container
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      DB_URI: mongodb://mongo_db:27017/
    depends_on:
      - mongo_db

volumes:
  mongo_db: {} 